baseURL                = '/'     
defaultContentLanguage = 'en'    
languageCode           = 'en-us' 
paginate               = 10      # number of blog post per page
theme                  = 'pico'  
themesDir              = '../..' 
title                  = 'Pico'  

[params]
customCSS = [
	"style/style.css",
	"style/theme.sass",
] # Path relative to assets folder

customJS = ["js/console.js"] # Path relative to assets folder

email   = "example@mail.com"
favicon = '/favicon.png'

	[[params.social]]
	alt  = "email icon"
	icon = "/icons/email.svg"
	name = "email"
	url  = "mailto:example@mail.com"

	[[params.social]]
	alt   = "github icon"
	blank = true
	icon  = "/icons/github.svg"
	name  = "github"
	url   = "https://github.com/negrel/"

	[[params.social]]
	alt   = "medium icon"
	blank = true
	icon  = "/icons/medium.svg"
	name  = "medium"
	url   = "https://medium.com/@negrel/"

	[[params.social]]
	alt   = "stack-overflow icon"
	blank = true
	icon  = "/icons/stack-overflow.svg"
	name  = "stack-overflow"
	url   = "https://stackoverflow.com/users/11627098/negrel"

	[[params.social]]
	alt   = "twitter icon"
	blank = true
	icon  = "/icons/twitter.svg"
	name  = "twitter"
	url   = "https://twitter.com/Twitter"

	[[params.social]]
	alt   = "facebook icon"
	blank = true
	icon  = "/icons/facebook.svg"
	name  = "facebook"
	url   = "https://facebook.com/"

[menu]

	[[menu.main]]
	identifier = "home" # identifier is use for translations
	pre        = ""     # pre is inserted before the translation (icons, image, etc)
	url        = "/"    
	weight     = 10     

	[[menu.main]]
	identifier = "blog"   # identifier is use for translations
	pre        = ""       # pre is inserted before the translation (icons, image, etc)
	url        = "/blog/" 
	weight     = 20       

	[[menu.main]]
	identifier = "about"  # identifier is use for translations
	pre        = ""       # pre is inserted before the translation (icons, image, etc)
	url        = "/about" 
	weight     = 30       

	[[menu.main]]
	identifier = "contact"   # identifier is use for translations
	pre        = ""          # pre is inserted before the translation (icons, image, etc)
	url        = "/#contact" 
	weight     = 40          

[markup.highlight]
guessSyntax        = true  
lineNumbersInTable = true  
noClasses          = false # Set to false to use the Pico default theme.
tabWidth           = 2     

[taxonomies]
category = "categories"
tag      = "tags"

[languages.en]
contentDir   = 'content/en'
languageCode = 'en'
languageName = 'English'
weight       = 0

[languages.fr]
contentDir   = 'content/fr'
languageCode = 'fr'
languageName = 'Français'
weight       = 2
