baseURL = '/'
languageCode = 'en-us'
title = 'Pico'
themesDir = '../..'
theme = 'pico'
defaultContentLanguage = 'en'
paginate = 10 # number of blog post per page

[params]
favicon = '/favicon.png'
customCSS = [
	"style/style.css",
	"style/theme.sass"
] # Path relative to assets folder
email = "example@mail.com"

[markup.highlight]
guessSyntax = true
lineNumbersInTable = true
noClasses = false # Set to false to use the Pico default theme.
tabWidth = 2

[taxonomies]
category = "categories"
tag = "tags"

[languages.en]
weight = 0
languageName = 'English'
languageCode = 'en'
contentDir = 'content/en'

[languages.fr]
weight = 2
languageName = 'Français'
languageCode = 'fr'
contentDir = 'content/fr'
