baseURL = '/'
languageCode = 'en-us'
title = 'Pico'
themesDir = '../..'
theme = 'pico'
defaultContentLanguage = 'en'

[params]
favicon = '/favicon.png'
customCSS = []

[markup.highlight]
guessSyntax = true
lineNumbersInTable = true
noClasses = false # Set to false to use the Pico default theme.
tabWidth = 2

[taxonomies]
category = "categories"
tag = "tags"

[languages.en]
weight = 0
languageName = 'English'
languageCode = 'en'
contentDir = 'content/en'

[languages.fr]
weight = 2
languageName = 'Français'
languageCode = 'fr'
contentDir = 'content/fr'
