baseURL = '/'
languageCode = 'en-us'
title = 'Pico'
themesDir = '../..'
theme = 'pico'
defaultContentLanguage = 'en'

[params]
favicon = '/svg/icon.svg'
customCSS = []
[languages.en]
weight = 0
languageName = 'English'
languageCode = 'en'
contentDir = 'content/en'

[languages.fr]
weight = 2
languageName = 'Français'
languageCode = 'fr'
contentDir = 'content/fr'
