baseURL = "/"
languageCode = "en-us"
title = "Pico"
themesDir = '../..'
theme = 'pico'

[params]
	# Your site icon (.ico, .png, .jpg, .svg, ...)
	# Favicon replace the site title of the header on small
	# device.
	favicon = "/svg/icon.svg"

